### ISSUE TITLE
OpenGL Error: invalid value 1281

### ISSUE THREAD

**Issue by kerigen** [Rajawali/RajawaliVuforia#31]
When I run my app for the first time on any device, everything runs ok .. the app start and works perfectly, but if I exit my app and run it again I get this ERROR:

FATAL EXCEPTION: GLThread 15673
java.lang.RuntimeException: OpenGL Error: invalid value 1281
at rajawali.renderer.RajawaliRenderer.onDrawFrame(RajawaliRenderer.java:387)
at rajawali.vuforia.RajawaliVuforiaRenderer.onDrawFrame(RajawaliVuforiaRenderer.java:124)
at com.example.test3d.MyRenderer.onDrawFrame(MyRenderer.java:50)
at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1516)
at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

this is my onDrawFrame function:

public void onDrawFrame(GL10 glUnused) {
    super.onDrawFrame(glUnused);
}

**Comment by fangyue** [comment]
Hi MasDennis, would you please share some mind on how this issue is caused and fixed? Because I might meet the same issue in new build of rajawali
