### ISSUE TITLE
Cannot load AWD file in RajawaliVuforiaExample

### ISSUE THREAD

**Issue by hoangminh1789** [Rajawali/RajawaliVuforia#69]
I deploy RajawaliVuforia to local maven successful. When I run RajawaliVuforiaExample, it has the error as above and crash app. How can I resolve?
Thanks.

```
12-31 01:37:17.559 17590-17747/? W/dalvikvm: VFY: register1 v8 type 17, wanted 18
12-31 01:37:17.559 17590-17747/? W/dalvikvm: VFY:  rejecting opcode 0x2d at 0x02ca
12-31 01:37:17.559 17590-17747/? W/dalvikvm: VFY:  rejected Lorg/rajawali3d/loader/awd/BlockTriangleGeometry;.parseBlock (Lorg/rajawali3d/loader/LoaderAWD$AWDLittleEndianDataInputStream;Lorg/rajawali3d/loader/LoaderAWD$BlockHeader;)V
12-31 01:37:17.559 17590-17747/? W/dalvikvm: Verifier rejected class Lorg/rajawali3d/loader/awd/BlockTriangleGeometry;
12-31 01:37:17.559 17590-17747/? W/System.err: java.lang.ClassNotFoundException: org.rajawali3d.loader.awd.BlockTriangleGeometry
12-31 01:37:17.569 17590-17747/? W/System.err:     at java.lang.Class.classForName(Native Method)
12-31 01:37:17.569 17590-17747/? W/System.err:     at java.lang.Class.forName(Class.java:217)
12-31 01:37:17.569 17590-17747/? W/System.err:     at java.lang.Class.forName(Class.java:172)
12-31 01:37:17.569 17590-17747/? W/System.err:     at org.rajawali3d.loader.LoaderAWD.parse(LoaderAWD.java:271)
12-31 01:37:17.569 17590-17747/? W/System.err:     at com.example.rajawalivuforiaexample.RajawaliVuforiaExampleRenderer.initScene(RajawaliVuforiaExampleRenderer.java:76)
12-31 01:37:17.569 17590-17747/? W/System.err:     at org.rajawali3d.renderer.RajawaliRenderer.onRenderSurfaceSizeChanged(RajawaliRenderer.java:348)
12-31 01:37:17.569 17590-17747/? W/System.err:     at org.rajawali3d.vuforia.RajawaliVuforiaRenderer.onRenderSurfaceSizeChanged(RajawaliVuforiaRenderer.java:59)
12-31 01:37:17.569 17590-17747/? W/System.err:     at com.example.rajawalivuforiaexample.RajawaliVuforiaExampleRenderer.onRenderSurfaceSizeChanged(RajawaliVuforiaExampleRenderer.java:179)
12-31 01:37:17.569 17590-17747/? W/System.err:     at org.rajawali3d.surface.RajawaliSurfaceView$RendererDelegate.onSurfaceChanged(RajawaliSurfaceView.java:221)
12-31 01:37:17.569 17590-17747/? W/System.err:     at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1455)
12-31 01:37:17.569 17590-17747/? W/System.err:     at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1216)
12-31 01:37:17.569 17590-17747/? W/System.err: Caused by: java.lang.VerifyError: org/rajawali3d/loader/awd/BlockTriangleGeometry
12-31 01:37:17.569 17590-17747/? W/System.err: 	... 11 more
12-31 01:37:17.569 17590-17747/? W/System.err: org.rajawali3d.loader.ParsingException: Unexpected error. File is not in a supported AWD format.
12-31 01:37:17.569 17590-17747/? W/System.err:     at org.rajawali3d.loader.LoaderAWD.parse(LoaderAWD.java:311)
12-31 01:37:17.579 17590-17747/? W/System.err:     at com.example.rajawalivuforiaexample.RajawaliVuforiaExampleRenderer.initScene(RajawaliVuforiaExampleRenderer.java:76)
12-31 01:37:17.579 17590-17747/? W/System.err:     at org.rajawali3d.renderer.RajawaliRenderer.onRenderSurfaceSizeChanged(RajawaliRenderer.java:348)
12-31 01:37:17.579 17590-17747/? W/System.err:     at org.rajawali3d.vuforia.RajawaliVuforiaRenderer.onRenderSurfaceSizeChanged(RajawaliVuforiaRenderer.java:59)
12-31 01:37:17.589 17590-17747/? W/System.err:     at com.example.rajawalivuforiaexample.RajawaliVuforiaExampleRenderer.onRenderSurfaceSizeChanged(RajawaliVuforiaExampleRenderer.java:179)
12-31 01:37:17.589 17590-17747/? W/System.err:     at org.rajawali3d.surface.RajawaliSurfaceView$RendererDelegate.onSurfaceChanged(RajawaliSurfaceView.java:221)
12-31 01:37:17.589 17590-17747/? W/System.err:     at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1455)
12-31 01:37:17.599 17590-17747/? W/System.err:     at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1216)
12-31 01:37:17.599 17590-17747/? W/System.err: Caused by: java.lang.ClassNotFoundException: org.rajawali3d.loader.awd.BlockTriangleGeometry
12-31 01:37:17.599 17590-17747/? W/System.err:     at java.lang.Class.classForName(Native Method)
12-31 01:37:17.599 17590-17747/? W/System.err:     at java.lang.Class.forName(Class.java:217)
12-31 01:37:17.599 17590-17747/? W/System.err:     at java.lang.Class.forName(Class.java:172)
12-31 01:37:17.599 17590-17747/? W/System.err:     at org.rajawali3d.loader.LoaderAWD.parse(LoaderAWD.java:271)
12-31 01:37:17.599 17590-17747/? W/System.err: 	... 7 more
12-31 01:37:17.599 17590-17747/? W/System.err: Caused by: java.lang.VerifyError: org/rajawali3d/loader/awd/BlockTriangleGeometry
12-31 01:37:17.599 17590-17747/? W/System.err: 	... 11 more
```

**Comment by ToxicBakery** [comment]
`java.lang.ClassNotFoundException: org.rajawali3d.loader.awd.BlockTriangleGeometry`

Looks like you are missing the core Rajawali dependency.

**Comment by hoangminh1789** [comment]
Thank to ToxicBakery.

I has already download Rajawali as Zip and run command 'gradle assembleRelease uploadArchives' to upload to mavenLocal. The result, I have some file in repository like this: 'm2\repository\org\rajawali3d\rajawali\1.0.0-SNAPSHOT'
- When I run RajawaliVuforiaExample its thows exception 
```
java.lang.ClassNotFoundException: org.rajawali3d.loader.awd.BlockTriangleGeometry'. 
```
- I comment maven link snapshot(in project RajawaliVuforia) to try use local Rajawali  and rebuild RajawaliVuforia
```
allprojects {
    repositories {
        mavenLocal()
        jcenter()
        //maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
    }
}
```
and I has result as:
```
A problem occurred configuring project ':rajawalivuforia'.
> Could not resolve all dependencies for configuration ':rajawalivuforia:_debugCompile'.
   > Could not find org.rajawali3d:rajawali:1.0.261-SNAPSHOT.
     Searched in the following locations:
         file:/C:/Users/HoangMinh/.m2/repository/org/rajawali3d/rajawali/1.0.261-SNAPSHOT/maven-metadata.xml
         file:/C:/Users/HoangMinh/.m2/repository/org/rajawali3d/rajawali/1.0.261-SNAPSHOT/rajawali-1.0.261-SNAPSHOT.pom
         file:/C:/Users/HoangMinh/.m2/repository/org/rajawali3d/rajawali/1.0.261-SNAPSHOT/rajawali-1.0.261-SNAPSHOT.aar
         https://jcenter.bintray.com/org/rajawali3d/rajawali/1.0.261-SNAPSHOT/maven-metadata.xml
         https://jcenter.bintray.com/org/rajawali3d/rajawali/1.0.261-SNAPSHOT/rajawali-1.0.261-SNAPSHOT.pom
         https://jcenter.bintray.com/org/rajawali3d/rajawali/1.0.261-SNAPSHOT/rajawali-1.0.261-SNAPSHOT.aar
         file:/D:/Work/tools/android-sdk-windows/extras/android/m2repository/org/rajawali3d/rajawali/1.0.261-SNAPSHOT/maven-metadata.xml
         file:/D:/Work/tools/android-sdk-windows/extras/android/m2repository/org/rajawali3d/rajawali/1.0.261-SNAPSHOT/rajawali-1.0.261-SNAPSHOT.pom
         file:/D:/Work/tools/android-sdk-windows/extras/android/m2repository/org/rajawali3d/rajawali/1.0.261-SNAPSHOT/rajawali-1.0.261-SNAPSHOT.aar
         file:/D:/Work/tools/android-sdk-windows/extras/google/m2repository/org/rajawali3d/rajawali/1.0.261-SNAPSHOT/maven-metadata.xml
         file:/D:/Work/tools/android-sdk-windows/extras/google/m2repository/org/rajawali3d/rajawali/1.0.261-SNAPSHOT/rajawali-1.0.261-SNAPSHOT.pom
         file:/D:/Work/tools/android-sdk-windows/extras/google/m2repository/org/rajawali3d/rajawali/1.0.261-SNAPSHOT/rajawali-1.0.261-SNAPSHOT.aar
     Required by:
         org.rajawali3d.vuforia:rajawalivuforia:1.0.0-SNAPSHOT
```

Can you show me how to run RajawaliVuforiaExample step by step?

**Comment by ToxicBakery** [comment]
In your dependencies just depend on the snapshot you built.

```org.rajawali3d:rajawali:1.0.0-SNAPSHOT```

**Comment by hoangminh1789** [comment]
Thanks ToxicBakery,
I was check, dependencies are correct. But I found in RajawaliVuforia/deps.gradle this content
```
project.ext.set('depRajawali', 'org.rajawali3d:rajawali:1.0.261-SNAPSHOT@aar')
```
I modify to 'org.rajawali3d:rajawali:1.0.0-SNAPSHOT@aar' and build success. But I still has exception
```
ava.lang.ClassNotFoundException: org.rajawali3d.loader.awd.BlockTriangleGeometry'.
```

Thank you so much, I continue do try.
