### ISSUE TITLE
libRajawaliVuforia.so could not be loaded

### ISSUE THREAD

**Issue by ushang000** [Rajawali/RajawaliVuforia#75]
hello
i copy libVuforia.so and libRajawaliVuforia.so in jniLibs folder
 when i run the sample RajawaliVuforiaExample,get log as below:

/com.example.rajawalivuforiaexample I/Rajawali: Native library libVuforia.so loaded
/com.example.rajawalivuforiaexample E/Rajawali: The library libRajawaliVuforia.so could not be loaded
com.example.rajawalivuforiaexample E/art: No implementation found for void org.rajawali3d.vuforia.RajawaliVuforiaActivity.setActivityPortraitMode(boolean) (tried Java_org_rajawali3d_vuforia_RajawaliVuforiaActivity_setActivityPortraitMode and Java_org_rajawali3d_vuforia_RajawaliVuforiaActivity_setActivityPortraitMode__Z)
/com.example.rajawalivuforiaexample D/AndroidRuntime: Shutting down VM
                                                      
                                                      
                                                      --------- beginning of crash
/com.example.rajawalivuforiaexample E/AndroidRuntime: FATAL EXCEPTION: main
                                                      Process: com.example.rajawalivuforiaexample, PID: 7420
                                                      java.lang.UnsatisfiedLinkError: No implementation found for void org.rajawali3d.vuforia.RajawaliVuforiaActivity.setActivityPortraitMode(boolean) (tried Java_org_rajawali3d_vuforia_RajawaliVuforiaActivity_setActivityPortraitMode and Java_org_rajawali3d_vuforia_RajawaliVuforiaActivity_setActivityPortraitMode__Z)
                                                          at org.rajawali3d.vuforia.RajawaliVuforiaActivity.setActivityPortraitMode(Native Method)
                                                          at org.rajawali3d.vuforia.RajawaliVuforiaActivity.initApplication(RajawaliVuforiaActivity.java:386)
                                                          at org.rajawali3d.vuforia.RajawaliVuforiaActivity.updateApplicationStatus(RajawaliVuforiaActivity.java:309)
                                                          at org.rajawali3d.vuforia.RajawaliVuforiaActivity.startVuforia(RajawaliVuforiaActivity.java:226)
                                                          at com.example.rajawalivuforiaexample.RajawaliVuforiaExampleActivity.onCreate(RajawaliVuforiaExampleActivity.java:38)
                                                          at android.app.Activity.performCreate(Activity.java:6303)
                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2376)
                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483)
                                                          at android.app.ActivityThread.access$900(ActivityThread.java:153)
                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                          at android.os.Looper.loop(Looper.java:148)
                                                          at android.app.ActivityThread.main(ActivityThread.java:5438)
                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by ushang000** [comment]
i rebuild rajawalivuforia with Vuforia SDK 6.2.10,  output libs folder contain libVuforia.so and libRajawaliVuforia.so file. i copy these files into RajawaliVuforiaExample module path src/main/jniLibs/.
then i run this module,get log "The library libRajawaliVuforia.so could not be loaded"
pls help me
